#!/usr/bin/env python3
"""
依據 config/doc-generation.yaml 的 llms_txt 區段，
生成/更新 docs/llms.txt（符合 llmstxt.org 規格），
讓 Agent 快速理解系統結構，不須逐一讀檔。

CLI 用法：
    uv run python tools/llms_txt_generator.py            # 更新 docs/llms.txt
    uv run python tools/llms_txt_generator.py --dry-run  # 只印出，不寫檔
"""
from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

import yaml


_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_CONFIG_PATH = _PROJECT_ROOT / "config" / "doc-generation.yaml"


def _load_config() -> dict:
    if not _CONFIG_PATH.exists():
        raise FileNotFoundError(f"Config not found: {_CONFIG_PATH}")
    with _CONFIG_PATH.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data.get("llms_txt", {})


def _file_description(path: Path) -> str:
    """Best-effort one-line description from a file's first heading or docstring."""
    if not path.exists():
        return "（檔案不存在）"
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return "（無法讀取）"

    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# ") and len(stripped) > 2:
            return stripped[2:].strip()
        if stripped.startswith('"""') and len(stripped) > 6:
            return stripped[3:].rstrip('"').strip()
    return ""


def generate_llms_txt(cfg: dict, project_root: Path = _PROJECT_ROOT) -> str:
    """Build the llms.txt content string from config."""
    site_name = cfg.get("site_name", "Daily Digest Prompt")
    site_desc = cfg.get("site_description", "").strip()
    sections = cfg.get("sections", [])
    optional_paths = cfg.get("optional_paths", [])
    timestamp = datetime.now().astimezone().isoformat(timespec="seconds")

    lines: list[str] = [
        f"# {site_name}",
        "",
        f"> {site_desc}",
        "",
    ]

    for section in sections:
        title = section.get("title", "")
        paths = section.get("paths", [])
        lines.append(f"## {title}")
        for rel_path in paths:
            full = project_root / rel_path
            desc = _file_description(full)
            desc_str = f": {desc}" if desc else ""
            lines.append(f"- [{rel_path}]({rel_path}){desc_str}")
        lines.append("")

    if optional_paths:
        lines.append("## Optional")
        for rel_path in optional_paths:
            full = project_root / rel_path
            desc = _file_description(full)
            desc_str = f": {desc}" if desc else ""
            lines.append(f"- [{rel_path}]({rel_path}){desc_str}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by tools/llms_txt_generator.py — {timestamp}*")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate docs/llms.txt from config.")
    parser.add_argument("--dry-run", action="store_true", help="Print only, do not write file")
    args = parser.parse_args()

    cfg = _load_config()
    content = generate_llms_txt(cfg)

    if args.dry_run:
        print(content)
        return

    output_file = _PROJECT_ROOT / cfg.get("output_file", "docs/llms.txt")
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(content, encoding="utf-8")
    print(f"✓ {output_file} updated ({len(content)} chars)")


if __name__ == "__main__":
    main()
